In [ ]:
!pip install jupyterthemes

In [ ]:
!jt -t monokai -T -N -kl #changing theme

In [ ]:
!jt -r  #change to default

In [1]:
l=[1,2,3,4,5,6,7,8]
l+l


[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
l=[1,2,3,4,5,6,7]
l[-1:-5:-1]

[7, 6, 5, 4]

In [9]:
l=[[1,2,3],[4,5,6,[4,4,8,9]],[7,8,9]]
l[1][3][0]

l=[1,2,3,4,5,6,7]
l[2:100]


[3, 4, 5, 6, 7]

In [10]:

l1=[1, 2 ,3]
l2= [4 ,5, 6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [13]:
2.l=[1,5,0]
for i in range(len(l)):
    l[i]=l[i]*2
l

[2, 10, 0]

In [ ]:



l=[1,5,0]

for i in range(len(l)):#[0,1,2]
    l[i]=2*l[i]
l

In [ ]:
l=[[10 ,1, 4 ,3], 
   [4 , 5, 1, 1],
   [3 , 3, 1 ,1 ]]
l

In [ ]:
[1,2,3,4]+[5,6,7,8]

# Numpy

input => learning => output


 <img src="3.png" width="800">


<img src="8.png" width="700" align="left">


bag of words



<img src="9.png" width="800" align="right">


<img src="10_.png" width="500" align="center">


In [1]:
import numpy as np

In [3]:
#[1,2,3,4]+[1,2,3,4] #[1,2,3,4,1,2,3,4]
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [ ]:
import numpy as np

In [5]:
vector=np.array([1,2,3])  #   یک لیستی که سه عنصر دارد
vector
#(3,)


array([1, 2, 3])

In [17]:
vector.shape    

(3,)

In [ ]:
l=[1,2,3,4]
print(l[0:3])

In [ ]:
l=[1,2,3,4,5,6,7]
l[2:6]

In [1]:
import numpy as np

In [3]:

a=np.array([[1,2,3,4],
            [1,2,6,4],
            [1,2,8,4]])


#یک لیستی که سه عنصر دارد که هر عنصر آن، 4 عنصر دارد

a[0:2,3:]

array([[4],
       [4]])

In [ ]:
l=[12,13,14,15,16,17]
l[2:5]

In [8]:
matrix=np.array([[1,2,3,4],
                 [1,2,6,4],
                 [1,2,8,4]])
matrix[2: , 2]



array([8])

In [ ]:
matrix[0:2,2]

matrix=np.array([[1,2,3,4],
                 [1,2,6,4],
                 [1,2,8,4]])

matrix[0:2][2]

In [ ]:
matrix[0:1]

In [11]:

matrix=np.array([[1,2,3,4],
                 [1,2,6,4],
                 [1,2,8,4]])


matrix[0:2,2:4][0:1 ,1]


array([4])

In [ ]:
matrix[1,2] 
matrix[1][2]

In [ ]:
matrix[0,2] 
matrix[0][2]

In [ ]:
import numpy as np

matrix=np.array([[1,2,3,4],
                 [1,2,6,4],
                 [1,2,8,4]])

a=matrix[ [1,2],2 ]

matrix[[1,2]][2]

In [14]:

a=np.array(
      [[[9, 6, 6],
        [5, 5, 9],
        [9, 9, 9],
        [5, 7, 2]],
       [[3, 8, 7],
        [8, 3, 3],
        [4, 6, 7],
        [9, 1, 3]],
       [[2, 2, 2],
        [2, 5, 3],
        [2, 3, 2],
        [2, 1, 8]]])
a[0:2,1:3, 2]
#a[0:2,-1]
a[:2][: ,-1]


array([[5, 7, 2],
       [9, 1, 3]])

In [ ]:
l=[1,2,3,4]
l[3]
l[-1]

In [ ]:
l=[1,2,3,4,6,7,9,10]
l[  :50]

In [ ]:
import numpy as np

In [ ]:
# یک لیستی که دو تا آیتم دارد
#  که هر آیتم خودش سه آیتم دارد که هر کدام از آنها 5 آیتم دارد
import numpy as np

# دو ارایه ی 3*5 دارد

tensor=np.array([[[1,2,3,4,5], 
                  [1,2,3,4,5],
                  [1,2,3,4,5]],
                 [[1,2,3,4,6],
                  [1,2,3,4,6],
                  [1,2,3,4,6]],
                 [[1,2,3,4,7],
                  [1,2,3,4,7],
                  [1,2,3,4,7]],
                 [[1,2,3,4,8],
                  [1,2,3,4,8],
                  [1,2,3,4,8]],
                 [[1,2,3,4,9],
                  [1,2,3,4,9],
                  [1,2,3,4,9]]])
tensor[2:5 , : , 2:]
tensor[0:3 , 1:3][0:1]

In [ ]:
tensor.shape
tensor[0:3 , 1:3 , 1:5 ]

tensor[1] 

tensor[ : ,:2 , 0:3 ]


In [ ]:
tensor[:][2]

In [ ]:
tensor[:2 ,0:2]

In [ ]:
tensor[:2][0:2]

In [ ]:
tensor

In [31]:
# import numpy as np

a=np.array(
      [[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 6],
        [1, 2, 3, 4, 6],
        [1, 2, 3, 4, 6]],

       [[1, 2, 3, 4, 7],
        [1, 2, 3, 4, 7],
        [1, 2, 3, 4, 7]]])

a[0][1]
a[[0,2] , 1:3 ]
a[0 , 1:3 ]
a[[0,1,2],[1,2,3]]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 7]])

In [ ]:
a[0][1]

In [5]:
a[0:2][0:1]

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [ ]:
a[[0,2] , 1:3 ]

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])



In [15]:
import numpy as np
a=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
a.shape

(2, 5)

In [ ]:
a

In [18]:
np.where(a>3,0,1)


array([[1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
# a=1
b=5

vector=np.array([False ,2, 3. , 3] ) #یک لیستی که سه عنصر دارد
vector.dtype

dtype('float64')

In [ ]:
vector.dtype

In [ ]:
#a=np.random.randint(0,10,(4,4,3))
a=np.array(
    [[[5, 0, 7],
      [9, 9, 3],
      [8, 4, 7],
      [2, 2, 9]],
     [[9, 7, 7],
      [7, 4, 0],
      [1, 4, 9],
      [5, 9, 2]],
     [[5, 9, 5],
      [4, 4, 2],
      [7, 5, 3],
      [9, 6, 0]],
     [[9, 8, 2],
      [3, 9, 5],
      [8, 3, 3],
      [3, 3, 3]]])

a[0:4,0 , 2:]

# reshaping array

In [34]:
a=np.array([[1,2,3,4],
            [6,7,8,9]])

a=np.array([1,2,3,4,5,6,7,8])

a
b=a.reshape((2,4))
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:

b=a.reshape((2,4)) #np.reshape(a , (2,4))
b=np.reshape(a,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
matrix=np.array([[1,2],
                 [3,4],
                 [5,6]])
matrix
matrix.shape
a=np.array([2,2,3,4,5,6])

matrix[: , : :-1]

a=a[1::2]

matrix.reshape((6,1))
np.reshape(matrix , (6,1))

In [ ]:

matrix=matrix.reshape((1,3))  # np.reshape(matrix,(2,3))
matrix

In [ ]:
list(range(0,20))

In [35]:

a=np.reshape(np.array([[ 0,  1,  2,  3,  4],
                     [ 5,  6,  7,  8,  9],
                     [10, 11, 12, 13, 14],
                     [15, 16, 17, 18, 19]]),(1,20))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [67]:
a.shape
a 
l=[1,2,3,4,5,6,7,8,9]
l[-3:-1:-1]

[]

In [43]:
a=a.reshape((5,-1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
m=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]])

m.reshape((-1,10))

In [ ]:
m.reshape((-1,10))


In [ ]:
m.reshape((6,-1))

In [8]:
m=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]] ,ndmin=3)

m


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
m=np.array([1,2,3,4,5,6])



In [46]:
m=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]])

m[ : ,  np.newaxis ]

m[np.newaxis][np.newaxis]
m[np.newaxis ,  :2]
m[ 2: , np.newaxis]
m[ : , np.newaxis]
m[ np.newaxis ,:]
m[ : ][np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [ ]:
m[np.newaxis  ]
m[np.newaxis][np.newaxis]
m[np.newaxis,  :2]
m[ 2: , np.newaxis]
m[ : , np.newaxis]
m[ : ][np.newaxis]

In [23]:
m[ :,:,None ]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

# np.arange    


In [32]:
a=list(range(0,10,2))
a

a=np.array(range(0,10))
a=np.arange(0,10) #a=np.array([0,1,2,3,4,...,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array([100,4,11,10])

In [34]:
import numpy as np
a=range(10,101)
arr=np.array(a)

b=np.arange(10,101,54)
b

array([10, 64])

In [ ]:
list(range(10,-1, -1))

In [ ]:

a=range(0,20,3)
np.array(a)

In [ ]:
a=np.arange(0,20,3)  #step=3
a

# np.linspace
step type : float

In [ ]:
np.arange(0,20,3)

In [37]:
a=np.linspace(0,20,3)   # step=(end-start)/(num-1)   (20-0)/(3-1)=10 
a 


array([ 0., 10., 20.])

In [ ]:
20/7

# specific arrays
<p>np.ones</p>
<p>np.zeros</p>
<p>np.full</p>
<p>np.eye</p>

In [44]:
a=np.array([[1,1,1],
            [1,1,1]])
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3))

In [ ]:
3*'ali'
3*[1,2,3,4]
[1,2,3,4]+[1,2,3,4]+[1,2,3,4]

In [ ]:
np.ones(2)

In [ ]:
range(1,10,-1)

In [ ]:
a=np.arange(1000)
a=a.reshape((2,500))
a


In [48]:

5*[1,2]
5*np.array([1,2])
5*np.ones((2,3,5))


array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [49]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
5*np.ones((2,3))

In [57]:
 np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [61]:
a=np.eye(6)
a[0,5]
a[0][5]
a[[0,5]]
a[[0,2,5]]
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,4)

In [ ]:
 np.eye(6)[[0,0,3,0,3]]

In [ ]:
np.eye(4)

In [ ]:
np.ones((2,))
np.ones(2)
np.ones((2))
np.ones((2,3))
#np.ones(2,3) Error

In [ ]:
type((2,))

In [ ]:
np.eye(4)[[0,2,3]]

In [ ]:
np.eye(4)[[0,1,2,3]]

In [ ]:
np.eye(4).shape

In [ ]:

a=np.array([1,2,3,4,5,6,7,8], ndmin=3)
print(a)

In [ ]:
l=[1,2,3,4]
l[:3]

In [ ]:
a=np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]])
a



In [ ]:
b=a[2 : , 1:4]
b

In [ ]:

a=np.array([1,2,3,4,5,6,7,8])
a=a[: , None]
a.shape
a

In [ ]:
import numpy as np

a=np.array([[[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]] ] )
a=a[ : , np.newaxis ]
a

In [ ]:
z=np.zeros((1,2))
z

In [ ]:
import numpy as np
a=np.ones((2,3)) #
a

In [ ]:
2*np.ones((2,3,4,2))


In [65]:
#np.full((3,2,3),range(0,3))
np.full((3,2,5) ,2)
np.full(3,2)
np.full(3,(2,5,1))


array([2, 5, 1])

In [70]:
np.full((2,3),(2,5,1))

array([[2, 5, 1],
       [2, 5, 1]])

In [ ]:
np.full(2,3) #fill_value=3
#np.full(2,3,4) #Error
np.full((2,3),4)

In [ ]:
np.eye(3,7)  #matris e ghotri


In [ ]:
np.arange(2,10,3)

In [ ]:
np.linspace(0,220,5)   #  (220-0)/5-1

In [ ]:
tensor=np.array([
       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 2, 4, 6],
        [1, 2, 4, 4, 6],
        [1, 2, 2, 4, 6]],
       [[1, 2, 3, 4, 7],
        [1, 2, 3, 4, 7],
        [1, 2, 3, 4, 7]]])

In [ ]:
tensor[0][0]

In [ ]:
tensor

In [ ]:
tensor[0,1,2]
tensor[0][1][2]

In [ ]:
tensor[0:2,0:2,0:2]

In [ ]:
tensor[0:2][0][0]

# stack

In [76]:
a=np.ones((3,2))
b=np.zeros((3,5))
print(a)
print()
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [75]:
np.hstack((a,b))

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.]])

In [77]:
a=np.ones((2,3))
b=np.zeros((5,3))
print(a)
print()
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [78]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# concatenate

In [8]:
a=np.ones((3,3))
b=np.zeros((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
[[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
np.concatenate((a,b),axis=0) #vertical  

In [ ]:
a=np.ones((2,3))
np.concatenate((a,b),axis=1) #horizental

# np.random

In [ ]:
a=np.random.randint(0,10,(2,2,3))
a

In [ ]:
a=np.random.randint(1,2,(2,3,4)) #size=(2,3,4)
a
np.random.rand(3,2)



In [ ]:
print(a.dtype)
print(a.shape)

In [ ]:
a.dtype=float
a

In [ ]:
print(a.dtype)
print(a.shape)

In [ ]:
np.array([2.0,3.0]).dtype

In [ ]:
a=1.0*a
a.dtype

In [ ]:
a=np.array(
        [[[4., 7., 7., 4., 7., 9., 7., 1.],
          [9., 7., 1., 2., 1., 5., 3., 9.],
          [9., 3., 6., 4., 4., 8., 5., 8.]],

         [[7., 3., 4., 8., 3., 9., 9., 5.],
          [1., 2., 3., 4., 7., 1., 1., 8.],
          [6., 1., 8., 5., 2., 3., 9., 3.]]])

In [ ]:
a=np.array(
         [[4., 7., 7., 4., 7., 9., 7., 1.],
          [9., 7., 1., 2., 1., 5., 3., 9.],
          [9., 3., 6., 4., 4., 8., 5., 8.]])
a[[0,1] , [4,5]]

In [ ]:
a[0,1,0]

In [ ]:
a[0,1:]

In [ ]:
a[:-1,:-1,-2]

In [ ]:
a<0

In [ ]:
a[a<0]

In [ ]:
a=np.ones((3,6))
a[:,0]=2
a[: , 1::2]=5
a


In [ ]:
a[:  , :3 , 1]=np.zeros((3,1))
a

In [ ]:
import numpy as np

a=np.random.normal(10, 3 ,(2,3,4))
a

In [9]:
a=np.random.randint(1,7,(2,3,4))

a

array([[[5, 3, 2, 5],
        [5, 1, 1, 5],
        [2, 5, 3, 2]],

       [[3, 1, 5, 1],
        [3, 2, 5, 3],
        [5, 6, 6, 4]]])

In [ ]:
np.sort(a,axis=0)

In [13]:
a=np.array(
      [[[3, 6, 3, 2],
        [6, 5, 1, 2],
        [3, 6, 6, 4]],

       [[3, 6, 6, 1],
        [2, 6, 6, 1],
        [4, 3, 6, 2]]])
np.sort(a,axis=0)

array([[[3, 6, 3, 1],
        [2, 5, 1, 1],
        [3, 3, 6, 2]],

       [[3, 6, 6, 2],
        [6, 6, 6, 2],
        [4, 6, 6, 4]]])

In [ ]:
a=np.array(
      [[[3, 6, 3, 2],
        [6, 5, 1, 2],
        [3, 6, 6, 4]],

       [[3, 6, 6, 1],
        [2, 6, 6, 1],
        [4, 3, 6, 2]]])
np.sort(a,axis=2)

In [ ]:
a.reshape(3,8)

In [ ]:
a.reshape(4,6)

In [ ]:
a.reshape(1,24)

In [ ]:
a=np.random.randint(0,20,(2,3))

a.flatten() 

In [ ]:
a=np.arange(3,10)
a
b=np.arange(7)
print(a)
print(b)

In [ ]:
c=np.hstack([a,b])
c

In [15]:
#c=np.vstack([a,b])
c=np.array([[3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6]])
c

array([[3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6]])

In [18]:
np.delete(c,(0,1),axis=1)

array([[5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6]])

In [ ]:
np.delete(c,0,axis=1)

In [14]:
c=np.hstack([a,b])
c

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
np.delete(c,0,1)

In [ ]:
a=np.random.randint(1,4,(2,3,4))
a

In [ ]:
np.delete(a,1,1)

# math on numpy

In [ ]:
a=np.arange(0,6).reshape((6,1))
np.random.seed(0)
print(a.shape) #(3,5)  

b=np.random.randint(0,10,(6,6))
print(a,end=2*'\n')
print(b,end=2*'\n')
print(a+b)

In [ ]:
a[1,0]

In [ ]:
a[a<3]

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)


In [ ]:
np.add(a,b)

In [ ]:
a.add(b)

In [ ]:
a=np.arange(0,18).reshape(2,3,3) 
b=np.ones(3) #(2,3,3)
b+a


In [ ]:
a+5

In [ ]:
a=[2]
b=[1,2,3,4]
a+b

In [ ]:
a=np.array([2])
b=np.array([1,2,3,4])
a+b

In [ ]:
np.add(a,b)

In [ ]:
[[1],[2],[3]] + [4,1]

In [ ]:
np.add([[1],[2],[3]],[4,1])

In [ ]:
print(a)
print(b)

In [ ]:
a=np.arange(0,18).reshape(2,3,3) 
b=np.arange(3) #(2,3,3)
print(a , b,sep=2*'\n')


In [ ]:
np.multiply(a,b)
a*b


In [ ]:
a=np.arange(0,6).reshape(2,3)
b=np.random.randint(0,10,(3,2))
a,b

In [ ]:
a*b


In [ ]:
np.dot(a,b) 
np.matmul(a,b)
a@b

In [ ]:
'''
np.matmul(a,b)
a@b
'''

In [ ]:
a*b

In [ ]:
a=np.array([[1,2],
             [3,4]])
b=np.arange(1,7).reshape(2,3)

print(a)
print(b)

In [ ]:
a.dot(b) #np.dot(a,b)

In [ ]:
a.shape , b.shape
b.dot(a) #(3,2) (2,3)

In [ ]:
b.dot(a)

In [ ]:
np.divide(a,b)
a/b

In [ ]:
d=np.array([[2 ,3],
            [-1,6]])



np.linalg.det(d)

In [ ]:
a=np.array([[2 ,3,3],
            [-1,6,7],
            [ 1,2,3]])

np.linalg.det(a)

In [ ]:
d=np.array([[5 ,6],
            [2, 3]])
1/d


In [ ]:
d=np.array([[5 ,6],
            [2, 3]])



np.linalg.inv(d)


In [ ]:
2x=y
x=y/2
x*A=B
x=B*inv(A)

In [ ]:
x=np.array(['x1','x2'])
         
A=np.array([[3,3.5],
            [3.2,3.6]])
         
B=np.array([118.4 , 135.2])
         
x=B.dot(np.linalg.inv(A))        
x

In [ ]:
x=np.array([['x1'],
            ['x2']])
         
A=np.array([[3,3.2],
            [3.5,3.6]])
         
B=np.array([[118.4], 
            [135.2]])
         
x=np.linalg.inv(A).dot(B)        
x

In [ ]:
d=np.array([[2,3],[-1,6,1]])
np.linalg.det(d)

In [ ]:
a=np.random.randint(1,10,(3,2))

print(a)


In [ ]:

a=np.random.randint(1,10,(2,3))
print(a)

print(a.T) 

In [ ]:
a=np.random.randint(1,4,(3,2,2))
print(a)
a.T

In [ ]:
np.linalg.det(a)

In [ ]:
np.linalg.inv(a)

In [ ]:
import numpy as np
b=np.array([118.4,135.2])
a=np.array([[3,3.5],
            [3.2,3.6]])
c=b.dot(np.linalg.inv(a))
c

In [ ]:
np.std
np.median
np.var

In [ ]:
mu,sigma=0,0.2
np.random.randint()
a=np.random.normal(mu,sigma,4)

print(a)
np.mean(a)
np.median(a)

In [ ]:
a=np.random.randint(1,4,(3,2))
print(a)

In [ ]:
a

In [ ]:
print(np.max(a,axis=1))

In [ ]:
print(np.sum(a,axis=1))

In [ ]:
print(np.max(a,axis=0))

In [ ]:
print(np.argmin(a,axis=0))

In [ ]:
print(np.min(a,axis=0)) #[3,2] [3,2] [3,1] [3,3,3] [2,2,save1]

In [ ]:
np.max(a,axis=0)

In [ ]:
#print(np.sum(a,axis=2))

In [ ]:
#np.save('mehrbod.npy',a)
a=np.load('mehrbod.npy')
a

In [ ]:
import cv2
a=cv2.imread('dog.png')
a.shape


In [ ]:
img=Image.open('dog.png')
imgarray=np.array(img)
plt.imshow(imgarray)

#imgarray[: ,:,:3].shape

imgarray

In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
im=Image.open('dog.png')
#plt.imshow(np.array(im))
np.array(im)

In [ ]:
imgarray[: ,:,3]=155
plt.imshow(imgarray)

<img src="6.png" width="800">
